#!/usr/bin/env bash
# Build and run
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Set SIMULATOR_ID here to avoid doing it in both build and run
# shellcheck source=scripts/simulator
[[ -n "${SIMULATOR_ID:-}" ]] || source "$SCRIPT_DIR/simulator"

"$SCRIPT_DIR/build" && exec "$SCRIPT_DIR/run"
