#!/usr/bin/env bash
# Build the project
set -Eeuo pipefail
trap 'echo "${BASH_SOURCE[0]}: line $LINENO: $BASH_COMMAND: exitcode $?"' ERR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."
START_TIME=$(date +%s.%N)

# shellcheck source=scripts/simulator
[[ -n "${SIMULATOR_ID:-}" ]] || source "$SCRIPT_DIR/simulator"

PROJECT_FILE="$(fd "xcodeproj$" | head -1)"
xcodebuild \
    -project "$PROJECT_FILE" \
    -scheme App \
    -configuration Debug \
    -destination "platform=iOS Simulator,arch=arm64,id=$SIMULATOR_ID" \
    -parallelizeTargets \
    -jobs "$(sysctl -n hw.ncpu)" \
    CODE_SIGNING_ALLOWED=NO \
    -quiet \
    build

END_TIME=$(date +%s.%N)
ELAPSED_TIME=$(echo "$END_TIME - $START_TIME" | bc --mathlib | xargs printf "%.2f\n")
echo "✅ Build completed in $ELAPSED_TIME seconds!"
