#!/usr/bin/env bash
set -euo pipefail
START_TIME=$(date +%s.%N)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

echo "Installing build tools ..."
command -v direnv &>/dev/null || brew install direnv
command -v git-lfs &>/dev/null || brew install git-lfs
xcode-select -p &>/dev/null || xcode-select --install

# Configurating tools
git lfs install
"$SCRIPT_DIR/install-git-hooks"

# Set Xcode so that it writes derived data into the project directory.
# It's unfortunate that this has to be set globally, but other methods didn't work
echo "Configuration xcode..."
defaults write com.apple.dt.Xcode DerivedDataLocationStyle Custom
defaults write com.apple.dt.Xcode IDECustomDerivedDataLocation ".DerivedData"

# Make a logs directory that won't get deleted by git clean
mkdir -p "logs"
[[ -d "logs/.git" ]] || git init "logs" 1>/dev/null

END_TIME=$(date +%s.%N)
ELAPSED_TIME=$(echo "$END_TIME - $START_TIME" | bc --mathlib | xargs printf "%.2f\n")
echo "✅ Setup complete in $ELAPSED_TIME seconds."
