#!/usr/bin/env bash
set -euo pipefail
START_TIME=$(date +%s.%N)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

echo "🚀 Testing app..."
xcodebuild \
    test \
    -project Habitual/Habitual.xcodeproj \
    -scheme Habitual \
    -destination "platform=iOS Simulator,arch=arm64,id=F57EC888-735B-4165-8842-985CE251390D" \
    "$@"

END_TIME=$(date +%s.%N)
ELAPSED_TIME=$(echo "$END_TIME - $START_TIME" | bc --mathlib | xargs printf "%.2f\n")
echo "✅ Running in $ELAPSED_TIME seconds!"

